name: News Analysis

on:
  schedule:
    - cron: "0 * * * *" # every hour (change as needed)
  workflow_dispatch: # allow manual trigger

jobs:
  run-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore processed URLs cache
        uses: actions/cache@v4
        with:
          path: processed_urls.txt
          key: processed-urls-cache

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python learning_bot.py

      - name: Save processed URLs to cache
        uses: actions/cache@v4
        with:
          path: processed_urls.txt
          key: processed-urls-cache
